services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    # Suppression du port 3307 vers l'extérieur pour la sécurité (le backend y accède en interne)
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: factscope  
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db:3306/factscope
    # On retire le volume ./backend:/app pour la prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    container_name: vuejs_frontend
    ports:
      - "5173:5173" # Tu pourras changer en "80:5173" si tu veux taper juste l'IP
    # On retire les volumes ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
